# Generated by Django 3.2.18 on 2023-02-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onememos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='testcol',
        ),
    ]
