# Generated by Django 3.2.18 on 2023-02-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onememos', '0002_remove_users_testcol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onememo',
            name='update_Date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
