# Generated by Django 3.2.18 on 2023-02-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onememos', '0003_alter_onememo_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onememo',
            name='writer',
            field=models.CharField(max_length=100),
        ),
    ]
